# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Create_Word.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateWordWindow(object):
    def setupUi(self, CreateWordWindow):
        CreateWordWindow.setObjectName("CreateWordWindow")
        CreateWordWindow.resize(421, 222)
        CreateWordWindow.setMinimumSize(QtCore.QSize(421, 222))
        CreateWordWindow.setMaximumSize(QtCore.QSize(421, 222))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/x2w_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CreateWordWindow.setWindowIcon(icon)
        self.label_3 = QtWidgets.QLabel(CreateWordWindow)
        self.label_3.setGeometry(QtCore.QRect(15, 10, 86, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setPixmap(QtGui.QPixmap("../img/excel-icon-86x80.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateWordWindow)
        self.buttonBox.setGeometry(QtCore.QRect(250, 180, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.EndRowBox = QtWidgets.QLineEdit(CreateWordWindow)
        self.EndRowBox.setGeometry(QtCore.QRect(145, 190, 26, 20))
        self.EndRowBox.setObjectName("EndRowBox")
        self.FileBox = QtWidgets.QLineEdit(CreateWordWindow)
        self.FileBox.setGeometry(QtCore.QRect(17, 98, 340, 20))
        self.FileBox.setObjectName("FileBox")
        self.EndColBox = QtWidgets.QLineEdit(CreateWordWindow)
        self.EndColBox.setGeometry(QtCore.QRect(109, 190, 26, 20))
        self.EndColBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EndColBox.setObjectName("EndColBox")
        self.StartRowLabel = QtWidgets.QLabel(CreateWordWindow)
        self.StartRowLabel.setGeometry(QtCore.QRect(55, 172, 47, 13))
        self.StartRowLabel.setObjectName("StartRowLabel")
        self.EndColLabel = QtWidgets.QLabel(CreateWordWindow)
        self.EndColLabel.setGeometry(QtCore.QRect(111, 172, 47, 13))
        self.EndColLabel.setObjectName("EndColLabel")
        self.StartColBox = QtWidgets.QLineEdit(CreateWordWindow)
        self.StartColBox.setGeometry(QtCore.QRect(17, 190, 26, 20))
        self.StartColBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StartColBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StartColBox.setObjectName("StartColBox")
        self.SheetcomboBox = QtWidgets.QComboBox(CreateWordWindow)
        self.SheetcomboBox.setGeometry(QtCore.QRect(17, 146, 190, 22))
        self.SheetcomboBox.setObjectName("SheetcomboBox")
        self.label = QtWidgets.QLabel(CreateWordWindow)
        self.label.setGeometry(QtCore.QRect(38, 190, 20, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.StartRowBox = QtWidgets.QLineEdit(CreateWordWindow)
        self.StartRowBox.setGeometry(QtCore.QRect(53, 190, 26, 20))
        self.StartRowBox.setText("")
        self.StartRowBox.setObjectName("StartRowBox")
        self.TabBoxLabel = QtWidgets.QLabel(CreateWordWindow)
        self.TabBoxLabel.setGeometry(QtCore.QRect(17, 126, 150, 13))
        self.TabBoxLabel.setObjectName("TabBoxLabel")
        self.toolButton = QtWidgets.QToolButton(CreateWordWindow)
        self.toolButton.setGeometry(QtCore.QRect(363, 98, 42, 20))
        self.toolButton.setObjectName("toolButton")
        self.EndRowLabel = QtWidgets.QLabel(CreateWordWindow)
        self.EndRowLabel.setGeometry(QtCore.QRect(147, 172, 47, 13))
        self.EndRowLabel.setObjectName("EndRowLabel")
        self.StartCollabel = QtWidgets.QLabel(CreateWordWindow)
        self.StartCollabel.setGeometry(QtCore.QRect(19, 172, 47, 13))
        self.StartCollabel.setObjectName("StartCollabel")
        self.label_2 = QtWidgets.QLabel(CreateWordWindow)
        self.label_2.setGeometry(QtCore.QRect(130, 190, 20, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(CreateWordWindow)
        self.label_4.setGeometry(QtCore.QRect(320, 10, 86, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setPixmap(QtGui.QPixmap("../img/word-icon-86x80.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(CreateWordWindow)
        self.label_5.setGeometry(QtCore.QRect(98, 10, 226, 80))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../img/Arrors.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(CreateWordWindow)
        self.toolButton.clicked.connect(CreateWordWindow.browse_for_workbook)
        self.buttonBox.accepted.connect(CreateWordWindow.ok_button_clicked)
        self.buttonBox.rejected.connect(CreateWordWindow.cancel_button_clicked)
        self.FileBox.textChanged['QString'].connect(CreateWordWindow.populate_sheet_cmb)
        QtCore.QMetaObject.connectSlotsByName(CreateWordWindow)
        CreateWordWindow.setTabOrder(self.FileBox, self.toolButton)
        CreateWordWindow.setTabOrder(self.toolButton, self.SheetcomboBox)
        CreateWordWindow.setTabOrder(self.SheetcomboBox, self.StartColBox)
        CreateWordWindow.setTabOrder(self.StartColBox, self.StartRowBox)
        CreateWordWindow.setTabOrder(self.StartRowBox, self.EndColBox)
        CreateWordWindow.setTabOrder(self.EndColBox, self.EndRowBox)

    def retranslateUi(self, CreateWordWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateWordWindow.setWindowTitle(_translate("CreateWordWindow", "Excel2Word"))
        self.EndRowBox.setInputMask(_translate("CreateWordWindow", "900"))
        self.FileBox.setText(_translate("CreateWordWindow", "Enter file location"))
        self.EndColBox.setInputMask(_translate("CreateWordWindow", ">Aa"))
        self.StartRowLabel.setText(_translate("CreateWordWindow", "Row"))
        self.EndColLabel.setText(_translate("CreateWordWindow", "Col"))
        self.StartColBox.setInputMask(_translate("CreateWordWindow", ">Aa"))
        self.label.setText(_translate("CreateWordWindow", ":"))
        self.StartRowBox.setInputMask(_translate("CreateWordWindow", "900"))
        self.TabBoxLabel.setText(_translate("CreateWordWindow", "Choose Sheet name "))
        self.toolButton.setText(_translate("CreateWordWindow", "..."))
        self.EndRowLabel.setText(_translate("CreateWordWindow", "Row"))
        self.StartCollabel.setText(_translate("CreateWordWindow", "Col"))
        self.label_2.setText(_translate("CreateWordWindow", ":"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateWordWindow = QtWidgets.QDialog()
    ui = Ui_CreateWordWindow()
    ui.setupUi(CreateWordWindow)
    CreateWordWindow.show()
    sys.exit(app.exec_())
